version: '3.2'

services:

  web:
    image: reactql-app
    restart: always
    build: ./client
    user: node
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

  server:
    image: reactql-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile-server
    user: node
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
    volumes:
      - ./server:/usr/src/app

  db:
    image: mongo
