version: '3'

services:

    web:
      image: reactql-app
      restart: always
      build:
        context: ./client
        dockerfile: ./client/Dockerfile-client-dev
      volumes:
        - ./client:/usr/src/app
      user: node
      command: yarn start
      depends_on:
        - server

    server:
      image: reactql-server
      restart: always
      build:
        context: ./server
        dockerfile: ./server/Dockerfile-server
      volumes:
        - ./server:/usr/src/app
      user: node
      command: yarn start
      depends_on:
        - db
      environment:
        - DB_HOST=db

    db:
      image: mongo
