FROM node:6.9.5-alpine

# Prepare app directory
WORKDIR /usr/src/app
ADD ./ /usr/src/app

# Install Yarn and Node.js dependencies
RUN npm install yarn --global --no-progress --silent --depth 0 && \
    yarn --no-progress

# Expose the app port
EXPOSE 8080

# Start the app
CMD yarn start
